# This is a basic workflow to help you get started with Actions

name: test
on: 
  watch: [started]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: ip addr show
